# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruil}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Hern\303\241ndez"]
  s.date = %q{2010-09-26}
  s.description = %q{It provides a class to derivate the application resources
and a delegator that select the appropiate resource to answer
a request. Also, it include a templating adapter based on Tenjin.}
  s.email = %q{daniel@degu.cl}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "VERSION",
     "lib/ruil/delegator.rb",
     "lib/ruil/resource.rb",
     "lib/ruil/tenjin_template.rb",
     "rakefile",
     "test/delegator_test.rb",
     "test/resource_test.rb",
     "test/templates/a.desktop.html",
     "test/templates/a.mobile.html",
     "test/templates/b.desktop.html",
     "test/templates/b.mobile.html"
  ]
  s.homepage = %q{http://github.com/danielhz/ruil}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruil}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Basic tools for build web appplications on top of rack}
  s.test_files = [
    "test/resource_test.rb",
     "test/delegator_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

