# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruil}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Hern\303\241ndez"]
  s.date = %q{2011-02-22}
  s.description = %q{It provides a class to derivate the application resources
and a delegator that select the appropiate resource to answer
a request. Also, it include a templating adapter based on Tenjin.}
  s.email = %q{daniel@degu.cl}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "VERSION",
    "lib/ruil.rb",
    "lib/ruil/json_template.rb",
    "lib/ruil/path_info_parser.rb",
    "lib/ruil/register.rb",
    "lib/ruil/resource.rb",
    "lib/ruil/template.rb",
    "rakefile",
    "ruil.gemspec",
    "spec/json_template_spec.rb",
    "spec/model_resource_test.rb",
    "spec/resource_spec.rb",
    "spec/resource_templates/a.desktop.tenjin.html",
    "spec/resource_templates/a.mobile.tenjin.html",
    "spec/resource_templates/b.desktop.tenjin.html",
    "spec/resource_templates/b.mobile.tenjin.html",
    "spec/resource_templates/template_test.desktop.tenjin.html",
    "spec/resource_templates/test.desktop.tenjin.html",
    "spec/resource_templates/test.mobile.tenjin.html",
    "spec/template_spec.rb"
  ]
  s.homepage = %q{http://github.com/danielhz/ruil}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruil}
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Minimalist library to build web appplications on top of rack}
  s.test_files = [
    "spec/json_template_spec.rb",
    "spec/model_resource_test.rb",
    "spec/resource_spec.rb",
    "spec/template_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

